# Generated by Django 5.1 on 2024-09-05 06:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('CC', 'CREDIT CARD'), ('DC', 'DEBIT CARD'), ('MP', 'MPESA'), ('MC', 'MASTERCARD')], default='MP', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookings.bookings')),
            ],
        ),
    ]
